name: newswave
description: "News project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  share: ^2.0.4
  webview_flutter: ^3.0.0
  shared_preferences: ^2.0.12
  flutter_native_splash: ^2.3.9
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png

flutter_native_splash:
  image: assets/images/splash.png
  color: "42a5f5"
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"